### ISSUE TITLE
ClientOrderId can be a string too

### ISSUE THREAD

**Issue by projct1** [gietos/dostavista#1]
Hi)

ClientOrderId is not necessary to be integer.
It can be something like this: TB1232, MS3241, 424-324-531 etc.

**Comment by kstkn** [comment]
@rorc , thanks 👍

**Comment by projct1** [comment]
Btw, can you push this commit please? =)

**Comment by kstkn** [comment]
@rorc it's already included into version 0.6

**Comment by projct1** [comment]
@gietos Strange, but with `"gietos/dostavista": "^0.5.0"` and run `composer update` package are not updating.
Ok, i rewrite to "gietos/dostavista": "^0.6.0" and works, thx )
